import safaricom from '/safaricom.png'
import equity from '/equity.png'
import jumia from '/jumia.jpg'
import jiji from '/jiji.jpg'
import kili from '/kili.png'
import carre from '/carre.jpg'
import arse from '/arse.jpg'
import bale from '/bale.jpg'
import bidco from '/bidco.png'
import imax from '/imax.jpg'
import nike from '/nike.jpg'
import absa from '/absa.jpg'
import coop from '/coop.jpeg'
import family from '/family.png'
import im from '/im.png'
import kcb from '/kcb.png'
import mpesa from '/mpesa.jpg'
import stanbic from '/stanbic.png'

export default {safaricom, equity, jumia, jiji, kili, carre, arse, bale, bidco,imax,nike,coop,family,im,kcb,mpesa,stanbic,absa}